### ISSUE TITLE
Translation improvements + Compendium translation

### ISSUE THREAD

**Issue by Zakarik** [NarumiRM/knight-es#1]
Hello!
I'm Zakarik, the creator of the system.
First of all, congratulations for this module, it's great. I discovered it by chance.
I'd like to take this opportunity to inform you that with the last update (yesterday), new lines were created in the :

**Line 2248 to 2280 + Line 2277 + Line 2311 + Line 1300 to 1301**

That's it, I don't think I've forgotten any lines.
Next, for the compendium, I've included compatibility with Babele for the English version, which means that there are all the files you need to translate it. You can take them and translate them to get the complete Spanish translation of the compendium, and do the little integration in a script (as I did for the compendium) so that Babele recognizes and finds these files.

Once again, a job well done, and I'm delighted that my system is being used internationally! If there's anything you need, please don't hesitate to contact me.

PS: Sorry about my English, I mostly use a translator to help me.

**Comment by NarumiRM** [comment]
Thanks you! I'll check that new lines as soon as I can. I usually use an IDE to check changes between releases in the original French file when the system updates, but your help is really welcomed.

I was planning to translate the compendium now, but I first needed to understand how Babele works (I'm new to foundry scripting). Having the translation files already integrated is a huge help.

Thanks you for creating the system with a good translation support, I'm glad you liked this and took your time to tell me the changes in the version.
